travis:
  secure:
    BINSTAR_TOKEN: BTSiilx2yViqz4nFOphxgXN+J/GWczgNawgkUhP52OrOHw0J+BoYD9nGbgWqyKXJmmYpJmvnJT4q94PMEdbbUyOy26Wmtwp3ZDfbV+KCbgZU5Mm3ECveEJtyB66Q8PBY5waAKXtznZ5JjxiDfNFSmwnjVXLmhCPHb5T/LFIQYrSulD2iIaTHBml9kRXOAVMqJ/bazzBCquLnRZ3X9k/tbuq1H1yq95rsZQzx90LbDQIXBJSqgYOsd2XCdNKTxJLGlIZjGSMGMF4+DXuAy2IRNIeTxI7h1hz+OcQvYi1+4qplV0Y5dWQxX5W0UHHyUad0lnOZXvrfHyr2HlHJcCY4Rz9CS6qifWHd8sUD5WQFwlWAh7+Y7G4lEiLsd2uazWAuW/M0VPrfZXPHftM4WvwnpsUvqJm3+J738rN1aaGhIAG6bmkPTRgrvkh+4v1/rb/04YLuwbEjklZ5r00GJN6IaqgglafLHOGAjEcPyJWRTRYdHT6XCLxaMYdLCv3N5NniAJlEjmG0NVigFXr+lJybx657R5wUGLefzDD9rTNj8GgbCLZonKImFVuzEIeiaUZjc/MHTjkOx0NYs/z2+1/ItdAFfcS7CJmLrdiKNvk14CAE9N4gRm0PcuhiUQj5VQdxEyFnjYmGNd5ry0DGGPIlUO3zCMbEzQp5CIUKSYJcb3M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
